import { mutation, query } from "./_generated/server";
import { v } from "convex/values";

const LESSONS_DATA = [
  // ===== SCIENCE (1-7) =====
  { lessonId: 1, title: "The Solar System", category: "Science", content: "Our solar system consists of the Sun and everything that orbits it, including eight planets, dwarf planets, moons, asteroids, and comets. The four inner planets — Mercury, Venus, Earth, and Mars — are rocky, while the four outer planets — Jupiter, Saturn, Uranus, and Neptune — are gas and ice giants. Earth is the only planet known to support life, thanks to its liquid water, atmosphere, and magnetic field.", dayNumber: 1 },
  { lessonId: 2, title: "Photosynthesis Explained", category: "Science", content: "Photosynthesis is the process by which green plants, algae, and some bacteria convert light energy into chemical energy. Using sunlight, water (H₂O), and carbon dioxide (CO₂), plants produce glucose (C₆H₁₂O₆) and release oxygen (O₂) as a byproduct. This process occurs mainly in the chloroplasts of plant cells, where chlorophyll absorbs light. Photosynthesis is essential for life on Earth — it produces the oxygen we breathe and forms the base of most food chains.", dayNumber: 2 },
  { lessonId: 3, title: "Introduction to DNA", category: "Science", content: "DNA (Deoxyribonucleic Acid) is the molecule that carries genetic instructions for the development, functioning, and reproduction of all living organisms. It has a double-helix structure, resembling a twisted ladder. The \"rungs\" of the ladder are made of base pairs: Adenine (A) pairs with Thymine (T), and Cytosine (C) pairs with Guanine (G). The sequence of these bases determine the genetic code that makes each organism unique.", dayNumber: 3 },
  { lessonId: 4, title: "The Water Cycle", category: "Science", content: "The water cycle describes how water moves continuously through Earth's systems. It begins with evaporation, where the sun heats surface water, turning it into vapor. This vapor rises and cools, forming clouds through condensation. When clouds become heavy, precipitation occurs as rain, snow, or hail. Water then collects in rivers, lakes, and oceans, or seeps into the ground as groundwater. The cycle repeats endlessly, sustaining ecosystems worldwide.", dayNumber: 4 },
  { lessonId: 5, title: "Basics of Electricity", category: "Science", content: "Electricity is the flow of electrons through a conductor, typically a wire. It is measured in volts (V), amperes (A), and watts (W). There are two types: Direct Current (DC), where electrons flow in one direction, and Alternating Current (AC), where electrons change direction periodically. AC is used in homes and businesses because it transmits efficiently over long distances. Components like resistors, capacitors, and transistors control electrical flow in circuits.", dayNumber: 5 },
  { lessonId: 6, title: "Human Memory Types", category: "Science", content: "Human memory is broadly classified into three types: Sensory Memory holds fleeting impressions from our senses for a few seconds. Short-Term Memory (or Working Memory) retains about 7 items for roughly 20–30 seconds, allowing us to process information actively. Long-Term Memory stores information indefinitely — it includes Explicit Memory (facts and events we consciously recall) and Implicit Memory (skills and habits we perform automatically). Sleep plays a critical role in consolidating short-term memories into long-term storage.", dayNumber: 6 },
  { lessonId: 7, title: "Atoms & Elements", category: "Science", content: "Everything in the universe is made of atoms — the smallest unit of matter that retains the properties of an element. An atom consists of a nucleus (containing protons and neutrons) surrounded by electrons orbiting in shells. The number of protons defines the element: Hydrogen has 1, Carbon has 6, Oxygen has 8. The Periodic Table organizes all 118 known elements by atomic number. Elements combine to form molecules — for example, two hydrogen atoms and one oxygen atom make water (H₂O).", dayNumber: 7 },
  // ===== IT / TECHNOLOGY (8-14) =====
  { lessonId: 8, title: "How the Internet Works", category: "IT", content: "The internet is a global network of interconnected computers that communicate using standardized protocols like TCP/IP. When you visit a website, your browser sends a request to a DNS server to translate the domain name into an IP address. The request travels through routers and switches to reach the destination server, which sends back the requested data in small packets. These packets are reassembled by your browser to display the webpage. The World Wide Web (WWW) is just one service that runs on the internet, alongside email, file transfer, and streaming.", dayNumber: 8 },
  { lessonId: 9, title: "HTML & CSS Fundamentals", category: "IT", content: "HTML (HyperText Markup Language) is the backbone of every webpage. It uses tags like <h1>, <p>, and <div> to structure content into headings, paragraphs, and sections. CSS (Cascading Style Sheets) controls the visual presentation — colors, fonts, spacing, and layout. Together, HTML provides the skeleton and CSS provides the skin. Modern CSS features like Flexbox and Grid make it easy to create responsive layouts that adapt to different screen sizes. Every website you visit is built on this HTML + CSS foundation.", dayNumber: 9 },
  { lessonId: 10, title: "Introduction to Python", category: "IT", content: "Python is one of the most popular programming languages in the world, known for its clean and readable syntax. Created by Guido van Rossum in 1991, Python uses indentation instead of braces to define code blocks. It supports multiple paradigms: procedural, object-oriented, and functional programming. Python excels in data science, machine learning, web development (Django, Flask), and automation. Its vast library ecosystem (NumPy, Pandas, TensorFlow) makes it a go-to language for beginners and experts alike. Variables in Python are dynamically typed — you don't need to declare types explicitly.", dayNumber: 10 },
  { lessonId: 11, title: "Cybersecurity Basics", category: "IT", content: "Cybersecurity is the practice of protecting systems, networks, and data from digital attacks. Common threats include: Phishing (fake emails that trick you into revealing passwords), Malware (malicious software like viruses and ransomware), and DDoS attacks (overwhelming a server with traffic). Strong defenses include using complex passwords, enabling Two-Factor Authentication (2FA), keeping software updated, and using firewalls. Encryption converts data into unreadable code that only authorized parties can decrypt. The CIA Triad — Confidentiality, Integrity, and Availability — is the foundation of information security.", dayNumber: 11 },
  { lessonId: 12, title: "Databases Explained", category: "IT", content: "A database is an organized collection of data stored electronically. Relational databases (like MySQL and PostgreSQL) store data in tables with rows and columns, and use SQL (Structured Query Language) to query data. NoSQL databases (like MongoDB and Firebase) use flexible formats like JSON documents, key-value pairs, or graphs — ideal for unstructured data. Key concepts include: Primary Keys (unique identifiers for each record), Foreign Keys (linking tables together), and Indexes (speeding up searches). Most modern applications — from social media to banking — rely on databases to store and retrieve information.", dayNumber: 12 },
  { lessonId: 13, title: "What is Cloud Computing?", category: "IT", content: "Cloud computing delivers computing services — servers, storage, databases, networking, software — over the internet (\"the cloud\"). Instead of owning physical hardware, you rent resources from providers like AWS, Google Cloud, or Microsoft Azure. There are three main service models: IaaS (Infrastructure as a Service) provides virtual machines, PaaS (Platform as a Service) provides development platforms, and SaaS (Software as a Service) provides ready-to-use applications like Gmail or Dropbox. Cloud benefits include scalability, cost savings, and global accessibility. Most apps you use daily run on cloud infrastructure.", dayNumber: 13 },
  { lessonId: 14, title: "APIs and How They Work", category: "IT", content: "An API (Application Programming Interface) is a set of rules that allows different software applications to communicate with each other. Think of it as a waiter in a restaurant — you (the client) give your order (request) to the waiter (API), who delivers it to the kitchen (server) and brings back your food (response). REST APIs use HTTP methods: GET (retrieve data), POST (create data), PUT (update data), and DELETE (remove data). APIs return data usually in JSON format. Popular APIs include Google Maps, Twitter, and OpenWeather. APIs are the backbone of modern app integration.", dayNumber: 14 },
  // ===== LANGUAGE (15-18) =====
  { lessonId: 15, title: "English Word Origins", category: "Language", content: "The English language is a fascinating blend of words borrowed from many languages over centuries. About 29% of English words come from Latin (e.g., \"animal\", \"video\", \"exit\"), 29% from French (e.g., \"restaurant\", \"ballet\", \"café\"), and 26% from Germanic roots (e.g., \"house\", \"water\", \"bread\"). Greek contributed scientific terms like \"biology\", \"philosophy\", and \"democracy\". English also borrows from Arabic (\"algebra\", \"zero\"), Japanese (\"tsunami\", \"karaoke\"), and Hindi (\"jungle\", \"shampoo\"). This rich mixing makes English one of the most vocabulary-rich languages with over 170,000 words in active use.", dayNumber: 15 },
  { lessonId: 16, title: "Japanese Writing Systems", category: "Language", content: "Japanese uses three writing systems simultaneously: Hiragana, Katakana, and Kanji. Hiragana (ひらがな) consists of 46 characters representing syllables — used for native Japanese words and grammar. Katakana (カタカナ) also has 46 characters but is used for foreign loanwords, scientific terms, and emphasis (e.g., コーヒー = \"kōhī\" = coffee). Kanji (漢字) are Chinese characters adopted into Japanese — there are about 2,136 commonly used Kanji. A typical Japanese sentence mixes all three systems.", dayNumber: 16 },
  { lessonId: 17, title: "Spanish for Beginners", category: "Language", content: "Spanish is the world's second most spoken native language with over 480 million native speakers across 20+ countries. Unlike English, Spanish is phonetic — words are pronounced exactly as they are spelled. Nouns have gender: \"el libro\" (the book, masculine) vs \"la casa\" (the house, feminine). Verbs conjugate based on the subject: \"yo hablo\" (I speak), \"tú hablas\" (you speak), \"él habla\" (he speaks). Common phrases include: \"Hola\" (Hello), \"Gracias\" (Thank you), \"Por favor\" (Please), \"¿Cómo estás?\" (How are you?).", dayNumber: 17 },
  { lessonId: 18, title: "How Languages Evolve", category: "Language", content: "Languages are living systems that constantly change over time. Linguists study how languages evolve through: Sound changes (English \"knight\" was once pronounced with a hard K), Semantic shifts (the word \"nice\" originally meant \"foolish\" in the 13th century), and Borrowing (Japanese \"アルバイト\" comes from German \"Arbeit\"). Languages are grouped into families — Indo-European is the largest, including English, Spanish, Hindi, and Russian. New words are constantly created through technology (\"selfie\", \"bluetooth\", \"google\" as a verb).", dayNumber: 18 },
  // ===== NATURE (19-21) =====
  { lessonId: 19, title: "Coral Reefs: Rainforests of the Sea", category: "Nature", content: "Coral reefs are underwater ecosystems built by colonies of tiny animals called coral polyps. Despite covering less than 1% of the ocean floor, coral reefs support about 25% of all marine species. The Great Barrier Reef in Australia is the largest, stretching over 2,300 kilometers. Corals have a symbiotic relationship with algae called zooxanthellae, which live inside their tissues and provide them with food through photosynthesis. When ocean temperatures rise, corals expel these algae, turning white — a process called coral bleaching.", dayNumber: 19 },
  { lessonId: 20, title: "Volcanoes: Earth's Fiery Giants", category: "Nature", content: "Volcanoes are openings in Earth's crust where molten rock (magma), gases, and ash escape from below the surface. When magma reaches the surface, it's called lava. There are three main types: Shield volcanoes (broad and flat, like Mauna Loa in Hawaii), Stratovolcanoes (steep and explosive, like Mount Fuji), and Cinder Cone volcanoes (small and short-lived). Most volcanoes are found along the \"Ring of Fire\" — a 40,000 km horseshoe-shaped zone around the Pacific Ocean.", dayNumber: 20 },
  { lessonId: 21, title: "Tropical Rainforests", category: "Nature", content: "Tropical rainforests are the most biodiverse ecosystems on Earth, home to over 50% of all plant and animal species despite covering only 6% of Earth's surface. The Amazon Rainforest is the largest, spanning 5.5 million square kilometers across nine countries. Rainforests have four layers: the Emergent Layer (tallest trees reaching 60m+), the Canopy (dense umbrella of treetops), the Understory (small trees and shrubs in dim light), and the Forest Floor (decomposing leaves, fungi, and insects). Rainforests produce about 20% of the world's oxygen and act as massive carbon sinks.", dayNumber: 21 },
];

/** Seed lessons into the DB (idempotent — only runs if table is empty) */
export const seedLessons = mutation({
  args: {},
  handler: async (ctx) => {
    const existing = await ctx.db.query("lessons").first();
    if (existing) return { seeded: false, count: 0 };

    for (const lesson of LESSONS_DATA) {
      await ctx.db.insert("lessons", lesson);
    }
    return { seeded: true, count: LESSONS_DATA.length };
  },
});

/** Get all lessons */
export const getLessons = query({
  args: {},
  handler: async (ctx) => {
    return await ctx.db.query("lessons").collect();
  },
});

/** Get a single lesson by lessonId */
export const getLesson = query({
  args: { lessonId: v.number() },
  handler: async (ctx, { lessonId }) => {
    return await ctx.db
      .query("lessons")
      .withIndex("by_lessonId", (q) => q.eq("lessonId", lessonId))
      .first();
  },
});
